version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    privileged: true
    ports:
      - "5672:5672" # Port AMQP
      - "15672:15672" # RabbitMQ Management UI
    volumes:
      - ./rabbitmq_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq_config/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  cpp_app:
    build:
      context: ./cpp_app
    container_name: cpp_app
    depends_on:
      - rabbitmq

  python_app:
    build:
      context: ./python_app
    container_name: python_app
    depends_on:
      - rabbitmq